$terminal = kitty -d "$(hyprcwd)"
$fileManager = dolphin "$(hyprcwd)"
$menu = wofi --show drun --prompt Apps -I
$browser = librewolf
$screenshot = $HOME/.config/hypr/scripts/screenshot.sh
$randomWallpapers = $HOME/.config/hypr/scripts/random_wallpapers.sh
$logoutMenu = $HOME/.config/wlogout/logout_menu.sh 1
