layerrule = match:namespace logout_dialog|swaync-control-center|swaync-notification-window|waybar|wofi , blur on
layerrule = match:namespace logout_dialog|swaync-control-center|swaync-notification-window|waybar , ignore_alpha 0
layerrule = match:namespace logout_dialog , dim_around on

# windowrule = match:class ^(kitty), no_blur on

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = starting-torrent-dl
    match:class = org.qbittorrent.qBittorrent
    match:title = negative:(.*qBittorrent.*)
    float = on
    center = on
}
