music_directory "$HOME/Music/"
playlist_directory "$HOME/Playlists/"

db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"

audio_output {
    type "pipewire"
    name "PipeWire Sound Server"
}

audio_output {
    type                    "fifo"
    name                    "my_mpd_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

